<?php
/**
 * @file
 * Code for the GSB Feature Insights Quote FPP feature.
 */

include_once 'gsb_feature_insights_quote_fpp.features.inc';
/**
 * @file
 * Code for the GSB Feature Insights Quote FPP feature.
 */

/**
 * Implements hook_entity_info_alter().
 */

function gsb_feature_insights_quote_fpp_entity_info_alter(&$entity_info) {
  $entity_info['fieldable_panels_pane']['bundles']['insights_quote'] = array(
    'label' => t('Quote (Insights)'),
    'pane category' => t('GSB panes'),
    'pane top level' => TRUE, // set to true to make this show as a top level icon
    'admin' => array(
      'path' => 'admin/structure/fieldable-panels-panes/manage/%fieldable_panels_panes_type',
      'bundle argument' => 10,
      // Note that this has all _ replaced with - from the bundle name.
      'real path' => 'admin/structure/fieldable-panels-panes/manage/insights-quote',
      'access arguments' => array('administer fieldable panels panes'),
    ),
  );
}
